name: riscv32-x11

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cross compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-riscv64-linux-gnu g++-riscv64-linux-gnu

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER=riscv64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=riscv64-linux-gnu-g++ \
            -DCMAKE_C_FLAGS="-march=rv32ima -mabi=ilp32" \
            -DCMAKE_CXX_FLAGS="-march=rv32ima -mabi=ilp32" \
            -DBUILD_TESTING=OFF -DUSE_LVGL=ON -DLVGL_BACKEND=x11

      - name: Build
        run: cmake --build build
