name: Build (X11)

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake nasm libx11-dev libxext-dev
      - name: Configure
        run: cmake -S . -B build -DCMAKE_C_FLAGS="-std=gnu11" -DUSE_LVGL=ON -DLVGL_BACKEND=x11
      - name: Build
        run: cmake --build build -j $(nproc)
      - name: Run tests
        run: ctest --test-dir build --output-on-failure

